2023-10-18T23:26:14.161808+0300 || DEBUG || ---LOGED---
2023-10-18T23:35:57.767128+0300 || DEBUG || ---LOGED---
2023-10-18T23:36:02.269101+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> return_admin
2023-10-18T23:36:19.435500+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-18T23:42:17.691386+0300 || DEBUG || ---LOGED---
2023-10-18T23:44:40.979008+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-18T23:44:59.997236+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-18T23:45:09.872819+0300 || DEBUG || ---LOGED---
2023-10-18T23:45:15.259962+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-18T23:45:28.348400+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-18T23:45:33.149482+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-18T23:45:38.056003+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-18T23:49:36.180342+0300 || DEBUG || ---LOGED---
2023-10-18T23:50:57.323755+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-18T23:54:01.106517+0300 || DEBUG || ---LOGED---
2023-10-18T23:56:43.534860+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (11384), thread 'MainThread' (10724):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 35, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x0000026DD95B1440>
    └ <discord.client.Client object at 0x0000026DD889A750>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x0000026DD9681B20>
    │       └ <function run at 0x0000026DD7E76FC0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x0000026DD965DC60>
           │      └ <function Runner.run at 0x0000026DD7EC4A40>
           └ <asyncio.runners.Runner object at 0x0000026DD967F910>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000026DD7EC2520>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000026DD967F910>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000026DD7FDE5C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000026DD7EC42C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000026DD7E70360>
    └ <Handle <TaskStepMethWrapper object at 0x0000026DD968A650>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000026DD968A650>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000026DD968A650>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000026DD968A650>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164306096794632294 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x0000026DD9681A80>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 31, in on_message
    case '/регистрация' | '/registration': await send(registration(author_name, author_id, conditions))
                                                 │    │            │            │          └ 'Весяa'
                                                 │    │            │            └ 710395621688737892
                                                 │    │            └ 'elisey_iz_kkr'
                                                 │    └ <function registration at 0x0000026DD9681620>
                                                 └ <function on_message.<locals>.send at 0x0000026DD9682200>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 23, in registration
    MEMBERS = json.load(f)
              │    │    └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
              │    └ <function load at 0x0000026DD7FFD8A0>
              └ <module 'json' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py'>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x0000026DD7FFD800>
  File "<frozen codecs>", line 322, in decode

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 7: invalid continuation byte
2023-10-18T23:57:15.131450+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (11384), thread 'MainThread' (10724):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 35, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x0000026DD95B1440>
    └ <discord.client.Client object at 0x0000026DD889A750>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x0000026DD9681B20>
    │       └ <function run at 0x0000026DD7E76FC0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x0000026DD965DC60>
           │      └ <function Runner.run at 0x0000026DD7EC4A40>
           └ <asyncio.runners.Runner object at 0x0000026DD967F910>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000026DD7EC2520>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000026DD967F910>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000026DD7FDE5C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000026DD7EC42C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000026DD7E70360>
    └ <Handle <TaskStepMethWrapper object at 0x0000026DD968AB90>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000026DD968AB90>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000026DD968AB90>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000026DD968AB90>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164306229338853477 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x0000026DD9681A80>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 31, in on_message
    case '/регистрация' | '/registration': await send(registration(author_name, author_id, conditions))
                                                 │    │            │            │          └ 'Весяaer'
                                                 │    │            │            └ 710395621688737892
                                                 │    │            └ 'elisey_iz_kkr'
                                                 │    └ <function registration at 0x0000026DD9681620>
                                                 └ <function on_message.<locals>.send at 0x0000026DD9682200>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 23, in registration
    MEMBERS = json.load(f)
              │    │    └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
              │    └ <function load at 0x0000026DD7FFD8A0>
              └ <module 'json' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py'>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x0000026DD7FFD800>
  File "<frozen codecs>", line 322, in decode

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 7: invalid continuation byte
2023-10-19T00:07:52.749439+0300 || DEBUG || ---LOGED---
2023-10-19T00:08:09.409948+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:08:24.708752+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:08:32.897825+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:48:30.527541+0300 || DEBUG || ---LOGED---
2023-10-19T00:48:53.649074+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:49:01.476569+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:50:01.054829+0300 || DEBUG || ---LOGED---
2023-10-19T00:50:07.275193+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:55:59.726475+0300 || DEBUG || ---LOGED---
2023-10-19T00:56:07.522734+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (5292), thread 'MainThread' (13024):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 35, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001CD54D01440>
    └ <discord.client.Client object at 0x000001CD515C8FD0>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001CD54DD1A80>
    │       └ <function run at 0x000001CD535C6FC0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001CD54DADC60>
           │      └ <function Runner.run at 0x000001CD53614A40>
           └ <asyncio.runners.Runner object at 0x000001CD54DDEF10>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001CD53612520>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001CD54DDEF10>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001CD53B2E5C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001CD536142C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001CD535C0360>
    └ <Handle <TaskStepMethWrapper object at 0x000001CD54DDB160>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001CD54DDB160>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001CD54DDB160>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001CD54DDB160>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164321045407334422 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x000001CD54DD19E0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 31, in on_message
    case '/регистрация' | '/registration': await send(registration(author_name, author_id, conditions))
                                                 │    │            │            │          └ 'елисей'
                                                 │    │            │            └ 710395621688737892
                                                 │    │            └ 'elisey_iz_kkr'
                                                 │    └ <function registration at 0x000001CD54DD1580>
                                                 └ <function on_message.<locals>.send at 0x000001CD551663E0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 28, in registration
    MEMBERS = json.load(f)
              │    │    └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
              │    └ <function load at 0x000001CD53B4D8A0>
              └ <module 'json' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py'>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x000001CD53B4D800>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x000001CD53B4DB20>
           └ <json.decoder.JSONDecoder object at 0x000001CD53B79310>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x000001CD53B742B0>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x000001CD53B4DA80>
               └ <json.decoder.JSONDecoder object at 0x000001CD53B79310>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-10-19T00:57:11.110612+0300 || DEBUG || ---LOGED---
2023-10-19T00:57:12.826941+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (success)
2023-10-19T00:57:20.165061+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-19T00:57:23.802494+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-19T00:57:26.650563+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-19T00:57:31.315584+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> registration (fail)
2023-10-19T18:06:27.226960+0300 || DEBUG || ---LOGED---
2023-10-19T18:06:44.602400+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:06:56.686055+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-19T18:27:13.133713+0300 || DEBUG || ---LOGED---
2023-10-19T18:27:16.988691+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-19T18:44:18.711070+0300 || DEBUG || ---LOGED---
2023-10-19T18:44:28.386574+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-19T18:44:36.845530+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:46:13.895463+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:46:21.823401+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:47:05.209436+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:47:33.323019+0300 || DEBUG || ---LOGED---
2023-10-19T18:47:37.106830+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:47:47.967337+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:48:43.837777+0300 || DEBUG || ---LOGED---
2023-10-19T18:48:46.065395+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:50:41.499283+0300 || DEBUG || ---LOGED---
2023-10-19T18:50:45.114135+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:51:04.250620+0300 || DEBUG || ---LOGED---
2023-10-19T18:51:05.303286+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:53:12.619135+0300 || DEBUG || ---LOGED---
2023-10-19T18:53:14.504078+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:54:40.503124+0300 || DEBUG || ---LOGED---
2023-10-19T18:54:41.626464+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:55:48.556061+0300 || DEBUG || ---LOGED---
2023-10-19T18:55:48.681375+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:56:35.369945+0300 || DEBUG || ---LOGED---
2023-10-19T18:56:36.483893+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:57:49.961325+0300 || DEBUG || ---LOGED---
2023-10-19T18:57:51.932224+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:59:25.605786+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (success)
2023-10-19T18:59:25.638729+0300 || DEBUG || ---LOGED---
2023-10-19T18:59:40.787113+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:59:47.531627+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T18:59:56.453574+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-19T19:02:53.488507+0300 || DEBUG || ---LOGED---
2023-10-19T19:03:41.933352+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (19088), thread 'MainThread' (11180):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 36, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001783FD91440>
    └ <discord.client.Client object at 0x000001783FD9FB10>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001783FE76480>
    │       └ <function run at 0x000001783E65AFC0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001783FE3DC60>
           │      └ <function Runner.run at 0x000001783E6A4A40>
           └ <asyncio.runners.Runner object at 0x000001783F082850>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001783E6A2520>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001783F082850>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001783E7BE5C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001783E6A42C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001783E650360>
    └ <Handle <TaskStepMethWrapper object at 0x000001783FE6AF20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001783FE6AF20>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001783FE6AF20>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001783FE6AF20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164594735344795688 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x000001783FE763E0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 33, in on_message
    case '/изменить'    | '/change'      : await send(change(author_name, author_id, conditions))
                                                 │    │      │            │          └ ['елисей', 'елисейгодх', 'кондратийь', 'warlock']
                                                 │    │      │            └ 710395621688737892
                                                 │    │      └ 'elisey_iz_kkr'
                                                 │    └ <function change at 0x000001783FE75F80>
                                                 └ <function on_message.<locals>.send at 0x00000178401FA980>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 111, in change
    banloot = MEMBERS[old_screen_name][banloot]
              │       └ 'елисей'
              └ {'Empty': {'id': 123, 'name': 'zalupa', 'class': 'dk', 'char': 'zalupa', 'banloot': 0}, 'елисей': {'id': 710395621688737892, ...

UnboundLocalError: cannot access local variable 'banloot' where it is not associated with a value
2023-10-19T19:04:41.636339+0300 || DEBUG || ---LOGED---
2023-10-19T19:04:49.744311+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /change (success)
2023-10-19T19:05:01.064347+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /change (fail)
2023-10-19T19:05:23.081789+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /change (success)
2023-10-19T19:05:42.625533+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /change (success)
2023-10-19T23:17:54.191911+0300 || DEBUG || ---LOGED---
2023-10-19T23:18:19.324078+0300 || DEBUG || ---LOGED---
2023-10-19T23:35:17.408863+0300 || DEBUG || ---LOGED---
2023-10-19T23:37:21.750310+0300 || DEBUG || ---LOGED---
2023-10-19T23:42:30.426534+0300 || DEBUG || ---LOGED---
2023-10-20T00:02:54.583110+0300 || DEBUG || ---LOGED---
2023-10-20T00:06:18.950601+0300 || DEBUG || ---LOGED---
2023-10-20T00:06:20.629978+0300 || DEBUG || ---LOGED---
2023-10-20T00:06:41.296614+0300 || DEBUG || ---LOGED---
2023-10-20T00:06:54.586596+0300 || DEBUG || ---LOGED---
2023-10-20T00:07:45.327263+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.327263+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.329263+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.330263+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.332264+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.334768+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.337794+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.338794+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.350300+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:07:45.354804+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:14.839448+0300 || DEBUG || ---LOGED---
2023-10-20T00:10:16.865902+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.873904+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.875905+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.876905+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.877905+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.878906+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.884907+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.878906+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (17180), thread 'MainThread' (16108):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 37, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x00000220162E1300>
    └ <discord.client.Client object at 0x0000022012C28E10>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x00000220163AB880>
    │       └ <function run at 0x0000022014BA3060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000002201638CB80>
           │      └ <function Runner.run at 0x0000022014BF8AE0>
           └ <asyncio.runners.Runner object at 0x00000220163B4CD0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000022014BF65C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000220163B4CD0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000022014CDE480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000022014BF8360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000022014B98400>
    └ <Handle <TaskStepMethWrapper object at 0x00000220163B2F20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000220163B2F20>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000220163B2F20>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000220163B2F20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164671891479474226 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x00000220163AB7E0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 32, in on_message
    case '/участники'   | '/members'     : await send(return_members(author_name, author_id))
                                                 │    │              │            └ 710395621688737892
                                                 │    │              └ 'elisey_iz_kkr'
                                                 │    └ <function return_members at 0x00000220163AAC00>
                                                 └ <function on_message.<locals>.send at 0x00000220163ABBA0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 82, in return_members
    MEMBERS = open_json('members')
              └ <function open_json at 0x00000220162E77E0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 20, in open_json
    DICT = json.load(f)                                    # open
           │    │    └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
           │    └ <function load at 0x0000022014D53880>
           └ <module 'json' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py'>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='members.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x0000022014D53920>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x0000022014D53100>
           └ <json.decoder.JSONDecoder object at 0x0000022014B6B350>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x0000022014D65220>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x0000022014D531A0>
               └ <json.decoder.JSONDecoder object at 0x0000022014B6B350>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-10-20T00:10:16.889908+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:10:16.891909+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:37.768116+0300 || DEBUG || ---LOGED---
2023-10-20T00:12:42.652211+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.654212+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.658213+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.659213+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.661213+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.662214+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.664214+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.663214+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.675217+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:12:42.688219+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:00.924086+0300 || DEBUG || ---LOGED---
2023-10-20T00:13:03.144584+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.147585+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.149585+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.151586+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.154586+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.154586+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.158587+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.159588+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.175591+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:03.182593+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:41.316557+0300 || DEBUG || ---LOGED---
2023-10-20T00:13:43.203981+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.205981+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.210982+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.210982+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.211982+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.216984+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.217984+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.218984+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.221984+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:13:43.234987+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:15:33.936538+0300 || DEBUG || ---LOGED---
2023-10-20T00:20:09.507600+0300 || DEBUG || ---LOGED---
2023-10-20T00:20:18.153539+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (18288), thread 'MainThread' (13712):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 37, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001DB36C21300>
    └ <discord.client.Client object at 0x000001DB3351D350>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001DB36CFE840>
    │       └ <function run at 0x000001DB354E3060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001DB36CCDB70>
           │      └ <function Runner.run at 0x000001DB35538AE0>
           └ <asyncio.runners.Runner object at 0x000001DB35F172D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001DB355365C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001DB35F172D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001DB3561E480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001DB35538360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001DB354DC400>
    └ <Handle <TaskStepMethWrapper object at 0x000001DB36CF7F10>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001DB36CF7F10>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001DB36CF7F10>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001DB36CF7F10>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164674413514477610 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x000001DB36CFE7A0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 34, in on_message
    case '/пиксель'     | '/object'      : await send(return_object(author_name, author_id, conditions))
                                                 │    │             │            │          └ ['Воля', 'Смертоносного']
                                                 │    │             │            └ 710395621688737892
                                                 │    │             └ 'elisey_iz_kkr'
                                                 │    └ <function return_object at 0x000001DB36CFE340>
                                                 └ <function on_message.<locals>.send at 0x000001DB36D171A0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 139, in return_object
    Очередь: {np.join(f'{classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"]}' for looter in LOOT[conditions]["queue"])}
              │  │                                                                                   │    └ 'Воля Смертоносного'
              │  │                                                                                   └ {'Воля Смертоносного': {'slot': 'trinket', 'ilvl': 277, 'description': 'Если на персонаже: Снижает эффективность брони против...
              │  └ <method 'join' of 'str' objects>
              └ '\n'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 139, in <genexpr>
    Очередь: {np.join(f'{classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"]}' for looter in LOOT[conditions]["queue"])}
                                                                                           └ 'Zalupa'

KeyError: 'Zalupa'
2023-10-20T00:21:13.042500+0300 || DEBUG || ---LOGED---
2023-10-20T00:28:55.207422+0300 || DEBUG || ---LOGED---
2023-10-20T00:28:59.871468+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.872469+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.875469+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.876469+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.876469+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.878469+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.880470+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.881470+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.882471+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:28:59.892473+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T00:29:10.307554+0300 || DEBUG || ---LOGED---
2023-10-20T00:29:14.356462+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T00:57:43.510846+0300 || DEBUG || ---LOGED---
2023-10-20T00:57:46.484514+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T00:57:46.485514+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (fail)
2023-10-20T00:58:24.627759+0300 || DEBUG || ---LOGED---
2023-10-20T00:58:25.648988+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T00:58:25.648988+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (15240), thread 'MainThread' (2544):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 37, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x00000169AD201300>
    └ <discord.client.Client object at 0x00000169AC56AE50>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x00000169AD2DE7A0>
    │       └ <function run at 0x00000169ABAC3060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x00000169AD2ADB70>
           │      └ <function Runner.run at 0x00000169ABB18AE0>
           └ <asyncio.runners.Runner object at 0x00000169AC4F5AD0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000169ABB165C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000169AC4F5AD0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000169ABBFE480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000169ABB18360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000169ABABC400>
    └ <Handle <TaskStepMethWrapper object at 0x00000169AD2D7E20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000169AD2D7E20>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000169AD2D7E20>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000169AD2D7E20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164684008194584677 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x00000169AD2DE700>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 34, in on_message
    case '/пиксель'     | '/object'      : await send(return_object(author_name, author_id, conditions))
                                                 │    │             │            │          └ ['Воля', 'Смертоносного']
                                                 │    │             │            └ 710395621688737892
                                                 │    │             └ 'elisey_iz_kkr'
                                                 │    └ <function return_object at 0x00000169AD2DE2A0>
                                                 └ <function on_message.<locals>.send at 0x00000169AD2F7100>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 146, in return_object
    return (loot, '{files: ["' + {LOOT[conditions]["img"]} + '"]}')
            │                     │    └ 'Воля Смертоносного'
            │                     └ {'Воля Смертоносного': {'slot': 'trinket', 'ilvl': 277, 'caste': 'melee', 'description': 'Если на персонаже: Снижает эффектив...
            └ 'Воля Смертоносного\nслот: trinket\nilvl: 277\nкаста: melee\nЕсли на персонаже: Снижает эффективность брони противника против...

TypeError: can only concatenate str (not "set") to str
2023-10-20T01:00:01.427624+0300 || DEBUG || ---LOGED---
2023-10-20T01:00:04.864395+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T01:00:46.394398+0300 || DEBUG || ---LOGED---
2023-10-20T01:00:54.343181+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T01:06:57.359875+0300 || DEBUG || ---LOGED---
2023-10-20T01:07:01.861884+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T01:07:22.711070+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.713070+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.716070+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.720072+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.721072+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.722072+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.722072+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.722072+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.723072+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:07:22.734075+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:23.125461+0300 || DEBUG || ---LOGED---
2023-10-20T01:11:27.644473+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.646474+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.649474+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.652475+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.653475+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.653475+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.657476+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.660477+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.667479+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:11:27.678481+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:16.048659+0300 || DEBUG || ---LOGED---
2023-10-20T01:17:17.989094+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:17.989094+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:17.994095+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:17.995096+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:17.998096+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:18.002097+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:18.002097+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:18.008099+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:18.009099+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:17:18.011099+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:39.525632+0300 || DEBUG || ---LOGED---
2023-10-20T01:18:41.608099+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.608099+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.610099+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.615101+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.616101+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.616101+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.618102+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.621102+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.623103+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:18:41.626103+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:11.722010+0300 || DEBUG || ---LOGED---
2023-10-20T01:21:12.351151+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.353151+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.354152+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.356152+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.357153+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.361153+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.362154+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.363154+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.370155+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T01:21:12.393160+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T13:10:13.208777+0300 || DEBUG || ---LOGED---
2023-10-20T13:10:18.905985+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (fail)
2023-10-20T13:12:02.183845+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-20T13:12:14.903074+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T13:30:57.883553+0300 || DEBUG || ---LOGED---
2023-10-20T13:31:18.594249+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (fail)
2023-10-20T13:31:53.738861+0300 || DEBUG || ---LOGED---
2023-10-20T13:31:55.244899+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (19200), thread 'MainThread' (14620):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 37, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001D4E5681300>
    └ <discord.client.Client object at 0x000001D4E1FDD450>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001D4E575E840>
    │       └ <function run at 0x000001D4E3F43060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001D4E572DB70>
           │      └ <function Runner.run at 0x000001D4E3F98AE0>
           └ <asyncio.runners.Runner object at 0x000001D4E576C2D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001D4E3F965C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001D4E576C2D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001D4E44B2480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001D4E3F98360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001D4E3F3C400>
    └ <Handle <TaskStepMethWrapper object at 0x000001D4E5757FA0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001D4E5757FA0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001D4E5757FA0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001D4E5757FA0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164873628131790868 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x000001D4E575E7A0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 34, in on_message
    case '/пиксель'     | '/object'      : await send(return_object(author_name, author_id, conditions))
                                                 │    │             │            │          └ ['Воля', 'Смертоносного']
                                                 │    │             │            └ 710395621688737892
                                                 │    │             └ 'elisey_iz_kkr'
                                                 │    └ <function return_object at 0x000001D4E575E340>
                                                 └ <function on_message.<locals>.send at 0x000001D4E577B1A0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 151, in return_object
    Полутавшие: {np}{np.join(f'{classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"].title()} {lootban(looter)}' for looter in LOOT[conditions]["have"])}'''
                 │   │  │                                                                                                             │    └ 'Воля Смертоносного'
                 │   │  │                                                                                                             └ {'Воля Смертоносного': {'slot': 'trinket', 'ilvl': 277, 'caste': 'melee', 'description': 'Если на персонаже: Снижает эффектив...
                 │   │  └ <method 'join' of 'str' objects>
                 │   └ '\n'
                 └ '\n'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 151, in <genexpr>
    Полутавшие: {np}{np.join(f'{classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"].title()} {lootban(looter)}' for looter in LOOT[conditions]["have"])}'''
                                                                                                                            └ 'елисей'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 132, in lootban
    if MEMBERS[looter]["lootban"] != 0:
       │       └ 'елисей'
       └ {'Empty': {'id': 123, 'name': 'zalupa', 'class': 'dk', 'char': 'zalupa', 'banloot': 0}, 'елисей': {'id': 710395621688737892, ...

KeyError: 'lootban'
2023-10-20T13:32:41.486659+0300 || DEBUG || ---LOGED---
2023-10-20T13:32:42.256138+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (10484), thread 'MainThread' (12492):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 37, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001D3ACD91300>
    └ <discord.client.Client object at 0x000001D3A96DD450>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001D3ACE6E840>
    │       └ <function run at 0x000001D3AB653060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001D3ACE3DB70>
           │      └ <function Runner.run at 0x000001D3AB6A8AE0>
           └ <asyncio.runners.Runner object at 0x000001D3ACE7C2D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001D3AB6A65C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001D3ACE7C2D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001D3AB7C2480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001D3AB6A8360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001D3AB64C400>
    └ <Handle <TaskStepMethWrapper object at 0x000001D3ACE67FD0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001D3ACE67FD0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001D3ACE67FD0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001D3ACE67FD0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164873825041793105 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x000001D3ACE6E7A0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 34, in on_message
    case '/пиксель'     | '/object'      : await send(return_object(author_name, author_id, conditions))
                                                 │    │             │            │          └ ['Воля', 'Смертоносного']
                                                 │    │             │            └ 710395621688737892
                                                 │    │             └ 'elisey_iz_kkr'
                                                 │    └ <function return_object at 0x000001D3ACE6E340>
                                                 └ <function on_message.<locals>.send at 0x000001D3ACE8B1A0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 151, in return_object
    Полутавшие: {np}{np.join(f'{classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"].title()} {lootban(looter)}' for looter in LOOT[conditions]["have"])}'''
                 │   │  │                                                                                                             │    └ 'Воля Смертоносного'
                 │   │  │                                                                                                             └ {'Воля Смертоносного': {'slot': 'trinket', 'ilvl': 277, 'caste': 'melee', 'description': 'Если на персонаже: Снижает эффектив...
                 │   │  └ <method 'join' of 'str' objects>
                 │   └ '\n'
                 └ '\n'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 151, in <genexpr>
    Полутавшие: {np}{np.join(f'{classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"].title()} {lootban(looter)}' for looter in LOOT[conditions]["have"])}'''
                                                                                                                            └ 'елисей'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 133, in lootban
    return f':warning:ЛУТБАН:warning: - {MEMBERS[looter]["lootban"]} кд'

KeyError: 'lootban'
2023-10-20T13:33:11.759445+0300 || DEBUG || ---LOGED---
2023-10-20T13:33:12.077428+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:04:11.948380+0300 || DEBUG || ---LOGED---
2023-10-20T14:04:18.230309+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:04:29.021025+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:05:23.360609+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /give (fail)
2023-10-20T14:05:57.376252+0300 || DEBUG || ---LOGED---
2023-10-20T14:05:59.765309+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /give (fail)
2023-10-20T14:06:31.398184+0300 || DEBUG || ---LOGED---
2023-10-20T14:06:33.036362+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (10264), thread 'MainThread' (14092):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 38, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x0000027E5D121300>
    └ <discord.client.Client object at 0x0000027E5BB91B50>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x0000027E5D1FEC00>
    │       └ <function run at 0x0000027E5B9E3060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x0000027E5D1CDC60>
           │      └ <function Runner.run at 0x0000027E5BA38AE0>
           └ <asyncio.runners.Runner object at 0x0000027E5D1E2890>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000027E5BA365C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000027E5D1E2890>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000027E5BB56480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000027E5BA38360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000027E5B9DC400>
    └ <Handle <TaskStepMethWrapper object at 0x0000027E5D5D44F0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000027E5D5D44F0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000027E5D5D44F0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000027E5D5D44F0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164882342809186305 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x0000027E5D1FEB60>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 35, in on_message
    case '/отдать'      | '/give'        : await send(give_object(author_name, author_id, conditions))
                                                 │    │           │            │          └ ['воля', 'смертоносного']
                                                 │    │           │            └ 710395621688737892
                                                 │    │           └ 'elisey_iz_kkr'
                                                 │    └ <function give_object at 0x0000027E5D1FE700>
                                                 └ <function on_message.<locals>.send at 0x0000027E5D21B560>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 189, in give_object
    LOOT[conditions]["queue"]
    │    └ 'воля смертоносного'
    └ {'admins': [710395621688737892]}

KeyError: 'воля смертоносного'
2023-10-20T14:09:13.084738+0300 || DEBUG || ---LOGED---
2023-10-20T14:09:15.313301+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (18352), thread 'MainThread' (5596):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 38, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000002317A711300>
    └ <discord.client.Client object at 0x00000231791E1B50>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000002317A7EEC00>
    │       └ <function run at 0x0000023179073060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000002317A7BDC60>
           │      └ <function Runner.run at 0x00000231790B8AE0>
           └ <asyncio.runners.Runner object at 0x000002317A7D2890>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000231790B65C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002317A7D2890>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000231791A6480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000231790B8360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002317906C400>
    └ <Handle <TaskStepMethWrapper object at 0x000002317ABC4490>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000002317ABC4490>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000002317ABC4490>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000002317ABC4490>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164883023787986944 channel=<TextChannel id=866252762853670924 name='общее' position=1 nsfw=False news=False cat...
          └ <function on_message at 0x000002317A7EEB60>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 35, in on_message
    case '/отдать'      | '/give'        : await send(give_object(author_name, author_id, conditions))
                                                 │    │           │            │          └ ['воля', 'смертоносного']
                                                 │    │           │            └ 710395621688737892
                                                 │    │           └ 'elisey_iz_kkr'
                                                 │    └ <function give_object at 0x000002317A7EE700>
                                                 └ <function on_message.<locals>.send at 0x000002317A80B380>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 189, in give_object
    LOOT[conditions]["queue"]
    │    └ 'воля смертоносного'
    └ {'Воля Смертоносного': {'slot': 'trinket', 'ilvl': 277, 'caste': 'melee', 'description': 'Если на персонаже: Снижает эффектив...

KeyError: 'воля смертоносного'
2023-10-20T14:09:45.729941+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /give (success)
2023-10-20T14:19:30.871362+0300 || DEBUG || ---LOGED---
2023-10-20T14:19:45.145461+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /lootban (success)
2023-10-20T14:19:54.521015+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T14:20:02.960723+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /lootban (success)
2023-10-20T14:20:07.670635+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T14:33:30.884727+0300 || DEBUG || ---LOGED---
2023-10-20T14:33:50.331467+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /registration (success)
2023-10-20T14:33:56.935960+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T14:34:30.756374+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /change (success)
2023-10-20T14:34:51.243978+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (fail)
2023-10-20T14:35:12.101534+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (fail)
2023-10-20T14:35:48.155312+0300 || DEBUG || ---LOGED---
2023-10-20T14:35:49.788796+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:38:04.695244+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /lootban (success)
2023-10-20T14:38:16.187720+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (fail)
2023-10-20T14:38:22.445658+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:38:49.058629+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /give (success)
2023-10-20T14:38:55.068579+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:40:24.463204+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /members (success)
2023-10-20T14:43:32.114937+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T14:43:48.233341+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /give (success)
2023-10-20T15:05:51.826948+0300 || DEBUG || ---LOGED---
2023-10-20T15:05:53.864983+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (fail)
2023-10-20T15:06:20.436562+0300 || DEBUG || ---LOGED---
2023-10-20T15:06:21.838382+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (15208), thread 'MainThread' (4744):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 39, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001A6FC4E1260>
    └ <discord.client.Client object at 0x000001A6F8DD14D0>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001A6FC5BEE80>
    │       └ <function run at 0x000001A6FADA2FC0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001A6FC58DC60>
           │      └ <function Runner.run at 0x000001A6FADF8A40>
           └ <asyncio.runners.Runner object at 0x000001A6FB8567D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001A6FADF6520>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001A6FB8567D0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001A6FB3163E0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001A6FADF82C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001A6FAD9C360>
    └ <Handle <TaskStepMethWrapper object at 0x000001A6FC994AC0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001A6FC994AC0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001A6FC994AC0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001A6FC994AC0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1164897396203982909 channel=<TextChannel id=1164886134137045024 name='общее' position=1 nsfw=False news=False ca...
          └ <function on_message at 0x000001A6FC5BEDE0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 34, in on_message
    case '/пиксель'     | '/object'      : await send(return_object(author_name, author_id, conditions))
                                                 │    │             │            │          └ ['воля', 'смертоносного']
                                                 │    │             │            └ 710395621688737892
                                                 │    │             └ 'elisey_iz_kkr'
                                                 │    └ <function return_object at 0x000001A6FC5BE200>
                                                 └ <function on_message.<locals>.send at 0x000001A6FC5DF920>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 156, in return_object
    Очередь: {np}{np.join(f'{return_count(looter)}. {classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"].title()} {lootban_object(looter)}' for looter in LOOT[conditions]["queue"])}
              │   │  │                                                                                                                                            │    └ 'воля смертоносного'
              │   │  │                                                                                                                                            └ {'воля смертоносного': {'slot': 'trinket', 'ilvl': 277, 'caste': 'melee', 'description': 'Если на персонаже: Снижает эффектив...
              │   │  └ <method 'join' of 'str' objects>
              │   └ '\n'
              └ '\n'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 156, in <genexpr>
    Очередь: {np}{np.join(f'{return_count(looter)}. {classes[MEMBERS[looter]["class"]]} {MEMBERS[looter]["char"].title()} {lootban_object(looter)}' for looter in LOOT[conditions]["queue"])}
                                                                                                                                                        └ 'сыч'

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 138, in return_count
    while MEMBERS.keys()[count] != looter:
          │       │      │         └ 'сыч'
          │       │      └ 0
          │       └ <method 'keys' of 'dict' objects>
          └ {'Empty': {'id': 123, 'name': 'zalupa', 'class': 'dk', 'char': 'zalupa', 'banloot': 0}, 'елисей': {'id': 710395621688737892, ...

TypeError: 'dict_keys' object is not subscriptable
2023-10-20T15:07:40.730397+0300 || DEBUG || ---LOGED---
2023-10-20T15:07:42.186034+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T15:10:21.430444+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T15:10:35.872611+0300 || DEBUG || ---LOGED---
2023-10-20T15:10:37.870602+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T15:11:19.115583+0300 || DEBUG || ---LOGED---
2023-10-20T15:11:21.113553+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T17:56:32.623789+0300 || DEBUG || ---LOGED---
2023-10-20T17:56:39.977438+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T17:57:23.717075+0300 || DEBUG || ---LOGED---
2023-10-20T17:57:26.367669+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T17:59:06.915710+0300 || DEBUG || ---LOGED---
2023-10-20T18:00:21.760381+0300 || DEBUG || ---LOGED---
2023-10-20T18:00:33.500015+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T18:01:46.577454+0300 || DEBUG || ---LOGED---
2023-10-20T18:02:39.469920+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T18:03:35.045956+0300 || DEBUG || ---LOGED---
2023-10-20T20:56:08.233540+0300 || DEBUG || ---LOGED---
2023-10-20T21:04:53.292927+0300 || DEBUG || ---LOGED---
2023-10-20T21:05:03.171143+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T21:12:43.122297+0300 || DEBUG || ---LOGED---
2023-10-20T21:12:49.053628+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T21:15:30.136949+0300 || DEBUG || ---LOGED---
2023-10-20T21:15:31.846332+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T21:16:23.534113+0300 || DEBUG || ---LOGED---
2023-10-20T21:16:25.654588+0300 || ERROR || An error has been caught in function 'on_raw_reaction_add', process 'MainProcess' (18488), thread 'MainThread' (8556):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 48, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001B3931513A0>
    └ <discord.client.Client object at 0x000001B3931D8C90>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001B393237600>
    │       └ <function run at 0x000001B391A23100>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001B3931FD300>
           │      └ <function Runner.run at 0x000001B391A6CB80>
           └ <asyncio.runners.Runner object at 0x000001B393229290>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001B391A6A660>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001B393229290>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001B391F8A520>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001B391A6C400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001B391A1C4A0>
    └ <Handle <TaskStepMethWrapper object at 0x000001B3935D5AE0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001B3935D5AE0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001B3935D5AE0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001B3935D5AE0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=11...
          └ <function on_raw_reaction_add at 0x000001B393237560>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 45, in on_raw_reaction_add
    await loot_by_reaction()
          └ <function loot_by_reaction at 0x000001B393236E80>

TypeError: loot_by_reaction() missing 3 required positional arguments: 'author_name', 'author_id', and 'emoji'
2023-10-20T21:16:52.344571+0300 || ERROR || An error has been caught in function 'on_raw_reaction_add', process 'MainProcess' (17364), thread 'MainThread' (17976):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 48, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000002A985F61300>
    └ <discord.client.Client object at 0x000002A985FEB1D0>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000002A986047560>
    │       └ <function run at 0x000002A984853060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000002A98600D300>
           │      └ <function Runner.run at 0x000002A98489CAE0>
           └ <asyncio.runners.Runner object at 0x000002A986039390>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000002A98489A5C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002A986039390>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002A98499A480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002A98489C360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002A98484C400>
    └ <Handle <TaskStepMethWrapper object at 0x000002A9863D98A0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000002A9863D98A0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000002A9863D98A0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000002A9863D98A0>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=11...
          └ <function on_raw_reaction_add at 0x000002A9860474C0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 45, in on_raw_reaction_add
    loot_by_reaction()
    └ <function loot_by_reaction at 0x000002A986046DE0>

TypeError: loot_by_reaction() missing 3 required positional arguments: 'author_name', 'author_id', and 'emoji'
2023-10-20T21:16:52.573623+0300 || DEBUG || ---LOGED---
2023-10-20T21:19:10.269142+0300 || DEBUG || ---LOGED---
2023-10-20T21:19:34.203866+0300 || DEBUG || ---LOGED---
2023-10-20T21:44:30.224556+0300 || DEBUG || ---LOGED---
2023-10-20T21:45:28.430359+0300 || DEBUG || ---LOGED---
2023-10-20T21:45:41.662744+0300 || DEBUG || ---LOGED---
2023-10-20T21:45:43.465148+0300 || ERROR || An error has been caught in function 'on_raw_reaction_add', process 'MainProcess' (14008), thread 'MainThread' (11232):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 47, in <module>
    client.run('MTEyMTUxMTYzMjAxOTkyMzA3Ng.Gy_7ab.eZDOkA-Z3yjb1Vs7a0PihwVa8cA2UGZfVCFkBM')
    │      └ <function Client.run at 0x000001E06DFB5300>
    └ <discord.client.Client object at 0x000001E06A8A3DD0>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001E06E0976A0>
    │       └ <function run at 0x000001E06C873060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001E06E05D300>
           │      └ <function Runner.run at 0x000001E06C8CCAE0>
           └ <asyncio.runners.Runner object at 0x000001E06E099150>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001E06C8CA5C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001E06E099150>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001E06CDEA480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001E06C8CC360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001E06C86C400>
    └ <Handle <TaskStepMethWrapper object at 0x000001E06E425A20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001E06E425A20>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001E06E425A20>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001E06E425A20>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=11...
          └ <function on_raw_reaction_add at 0x000001E06E097600>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 44, in on_raw_reaction_add
    loot_by_reaction(payload.member, payload.user_id, payload.emoji, payload.message_id)
    │                │       │       │       │        │       │      │       └ <member 'message_id' of 'RawReactionActionEvent' objects>
    │                │       │       │       │        │       │      └ <RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=116...
    │                │       │       │       │        │       └ <member 'emoji' of 'RawReactionActionEvent' objects>
    │                │       │       │       │        └ <RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=116...
    │                │       │       │       └ <member 'user_id' of 'RawReactionActionEvent' objects>
    │                │       │       └ <RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=116...
    │                │       └ <member 'member' of 'RawReactionActionEvent' objects>
    │                └ <RawReactionActionEvent message_id=1164990303556620421 user_id=710395621688737892 channel_id=1164886134137045024 guild_id=116...
    └ <function loot_by_reaction at 0x000001E06E096F20>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 256, in loot_by_reaction
    object_ = CASHE["give_object"][cashe_id]
              │                    └ 1164990303556620421
              └ {'give_object': {'1164940449711140997': 'воля смертоносного', '1164941234821943387': 'воля смертоносного', '11649417630903174...

KeyError: 1164990303556620421
2023-10-20T21:47:08.046753+0300 || DEBUG || ---LOGED---
2023-10-20T21:52:24.576497+0300 || DEBUG || ---LOGED---
2023-10-20T21:52:27.794219+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T21:52:38.169547+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> рома)
2023-10-20T21:52:45.225130+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T21:52:52.327723+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> транкшот)
2023-10-20T21:53:00.532960+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T21:53:15.391294+0300 || DEBUG || ---LOGED---
2023-10-20T21:53:19.516220+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> сыч)
2023-10-20T22:05:31.117527+0300 || DEBUG || ---LOGED---
2023-10-20T22:05:36.180662+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> какиш)
2023-10-20T22:06:03.536646+0300 || DEBUG || ---LOGED---
2023-10-20T22:06:06.062213+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:06:10.938307+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> катана)
2023-10-20T22:19:45.030695+0300 || DEBUG || ---LOGED---
2023-10-20T22:19:47.737216+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:19:54.083840+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> казах)
2023-10-20T22:26:20.881121+0300 || DEBUG || ---LOGED---
2023-10-20T22:26:24.729984+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:28:47.408779+0300 || DEBUG || ---LOGED---
2023-10-20T22:28:50.633503+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:29:57.371902+0300 || DEBUG || ---LOGED---
2023-10-20T22:30:03.762080+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:30:16.181314+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> транкшот)
2023-10-20T22:30:37.663532+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:30:51.105548+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-20T22:34:53.283818+0300 || DEBUG || ---LOGED---
2023-10-20T22:34:55.613340+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-21T00:04:25.587926+0300 || DEBUG || ---LOGED---
2023-10-21T00:04:27.484351+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /object (success)
2023-10-21T00:06:24.507672+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> Empty)
2023-10-21T00:06:26.037015+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> рома)
2023-10-21T00:06:27.260290+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> какиш)
2023-10-21T00:06:53.022987+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> елисей)
2023-10-21T00:06:54.979426+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /loot_by_reaction (воля смертоносного -> сыч)
2023-10-24T23:09:30.827004+0300 || DEBUG || ---LOGED---
2023-10-24T23:09:34.569535+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-24T23:10:33.770439+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-24T23:10:33.929482+0300 || DEBUG || ---LOGED---
2023-10-24T23:12:24.434822+0300 || DEBUG || ---LOGED---
2023-10-24T23:12:28.394189+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-24T23:17:42.112338+0300 || DEBUG || ---LOGED---
2023-10-24T23:17:43.718247+0300 || DEBUG || elisey_iz_kkr | 710395621688737892 --> /admins (success)
2023-10-26T23:37:11.549056+0300 || DEBUG || ---LOGED---
2023-10-26T23:37:33.228073+0300 || DEBUG || ---LOGED---
2023-10-27T00:17:15.421455+0300 || DEBUG || ---LOGED---
2023-10-27T00:22:55.740843+0300 || DEBUG || ---LOGED---
2023-10-27T00:24:00.217532+0300 || DEBUG || ---LOGED---
2023-10-27T00:26:56.723536+0300 || DEBUG || ---LOGED---
2023-10-27T00:28:05.662408+0300 || DEBUG || ---LOGED---
2023-10-27T18:34:52.108663+0300 || DEBUG || ---LOGED---
2023-10-27T18:35:26.352082+0300 || DEBUG || ---LOGED---
2023-10-27T18:37:29.983764+0300 || DEBUG || ---LOGED---
2023-10-27T18:38:21.049863+0300 || DEBUG || ---LOGED---
2023-10-27T18:40:05.249028+0300 || DEBUG || ---LOGED---
2023-10-27T18:52:49.345257+0300 || DEBUG || ---LOGED---
2023-10-27T18:54:36.155210+0300 || DEBUG || ---LOGED---
2023-10-27T19:02:00.693033+0300 || DEBUG || ---LOGED---
2023-10-29T17:34:43.471814+0300 || DEBUG || ---LOGED---
2023-10-30T00:11:01.539306+0300 || DEBUG || ---LOGED---
2023-10-30T18:31:44.217082+0300 || ERROR || An error has been caught in function 'on_ready', process 'MainProcess' (8340), thread 'MainThread' (15196):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 95, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x000001C19FCA53A0>
    └ <discord.client.Client object at 0x000001C19F007750>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001C19FD98220>
    │       └ <function run at 0x000001C19E567100>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001C19FD65D50>
           │      └ <function Runner.run at 0x000001C19E5BCB80>
           └ <asyncio.runners.Runner object at 0x000001C19C3C1550>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001C19E5BA660>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001C19C3C1550>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001C19EADA520>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001C19E5BC400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001C19E55C4A0>
    └ <Handle <TaskStepMethWrapper object at 0x000001C19FD93700>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001C19FD93700>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001C19FD93700>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001C19FD93700>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ ()
          └ <function on_ready at 0x000001C19FD7FF60>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 19, in on_ready
    language_initialization()
    └ <function language_initialization at 0x000001C19FD7D1C0>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 41, in language_initialization
    LANGUAGE = open_json('localization/content.json')
               └ <function open_json at 0x000001C19FCAF880>

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 29, in open_json
    with open(file +'.json', encoding='utf-8') as f:           #
              └ 'localization/content.json'

FileNotFoundError: [Errno 2] No such file or directory: 'localization/content.json.json'
2023-10-30T18:31:44.265094+0300 || DEBUG || ---LOGED---
2023-10-30T18:32:39.068138+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:32:39.069138+0300 || DEBUG || ---LOGED---
2023-10-30T18:35:26.446427+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:35:26.447428+0300 || DEBUG || ---LOGED---
2023-10-30T18:37:13.261004+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:37:13.262004+0300 || DEBUG || ---LOGED---
2023-10-30T18:39:30.266945+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:39:30.267946+0300 || DEBUG || ---LOGED---
2023-10-30T18:40:55.060187+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:40:55.061187+0300 || DEBUG || ---LOGED---
2023-10-30T18:50:34.944696+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:50:34.945697+0300 || DEBUG || ---LOGED---
2023-10-30T18:52:08.947104+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:52:08.948104+0300 || DEBUG || ---LOGED---
2023-10-30T18:53:25.542949+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T18:53:25.542949+0300 || DEBUG || ---LOGED---
2023-10-30T19:09:22.685362+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T19:09:22.685362+0300 || DEBUG || ---LOGED---
2023-10-30T19:22:53.866789+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T19:22:53.867789+0300 || DEBUG || ---LOGED---
2023-10-30T19:23:12.146270+0300 || ERROR || An error has been caught in function 'on_raw_reaction_add', process 'MainProcess' (14112), thread 'MainThread' (11428):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 106, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x000001E7159453A0>
    └ <discord.client.Client object at 0x000001E712305010>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001E715A38220>
    │       └ <function run at 0x000001E714257100>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001E715A05D50>
           │      └ <function Runner.run at 0x000001E7142A0B80>
           └ <asyncio.runners.Runner object at 0x000001E715A32150>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001E71429A660>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001E715A32150>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001E71478A520>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001E7142A0400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001E7142504A0>
    └ <Handle <TaskStepMethWrapper object at 0x000001E715A26C80>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001E715A26C80>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001E715A26C80>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001E715A26C80>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<RawReactionActionEvent message_id=1168585890499670066 user_id=710395621688737892 channel_id=1167491479745343528 guild_id=11...
          └ <function on_raw_reaction_add at 0x000001E715A380E0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 80, in on_raw_reaction_add
    GUILDS[str(payload.guild_id)].guild_language, dict_embed = new_guild(
    │          │       │                                       └ <function new_guild at 0x000001E715A1F740>
    │          │       └ <member 'guild_id' of 'RawReactionActionEvent' objects>
    │          └ <RawReactionActionEvent message_id=1168585890499670066 user_id=710395621688737892 channel_id=1167491479745343528 guild_id=116...
    └ {'1164886134137045022': <guilds.Guilds object at 0x000001E7159D45D0>}

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 306, in new_guild
    if flag is False:

UnboundLocalError: cannot access local variable 'flag' where it is not associated with a value
2023-10-30T19:33:21.906876+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T19:33:21.907876+0300 || DEBUG || ---LOGED---
2023-10-30T19:33:46.194783+0300 || ERROR || An error has been caught in function 'on_raw_reaction_add', process 'MainProcess' (6244), thread 'MainThread' (4728):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 112, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x000001E2773953A0>
    └ <discord.client.Client object at 0x000001E27668A950>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001E277484540>
    │       └ <function run at 0x000001E275C57100>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001E277459120>
           │      └ <function Runner.run at 0x000001E275CB0B80>
           └ <asyncio.runners.Runner object at 0x000001E277481890>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001E275CAA660>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001E277481890>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001E2761CA520>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001E275CB0400>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001E275C504A0>
    └ <Handle <TaskStepMethWrapper object at 0x000001E277831060>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001E277831060>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001E277831060>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001E277831060>()>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<RawReactionActionEvent message_id=1168588505232969729 user_id=710395621688737892 channel_id=1167491479745343528 guild_id=11...
          └ <function on_raw_reaction_add at 0x000001E277484400>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 86, in on_raw_reaction_add
    GUILDS[str(payload.guild_id)].guild_language, dict_embed = new_guild(
    │          │       │                                       └ <function new_guild at 0x000001E277477A60>
    │          │       └ <member 'guild_id' of 'RawReactionActionEvent' objects>
    │          └ <RawReactionActionEvent message_id=1168588505232969729 user_id=710395621688737892 channel_id=1167491479745343528 guild_id=116...
    └ {'1164886134137045022': <guilds.Guilds object at 0x000001E2743063D0>}

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\methods.py", line 306, in new_guild
    if flag is False:

UnboundLocalError: cannot access local variable 'flag' where it is not associated with a value
2023-10-30T19:39:25.578813+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T19:39:25.579813+0300 || DEBUG || ---LOGED---
2023-10-30T19:39:53.803947+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x0000023460B785E0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x0000023460ACAC00> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T19:59:33.993330+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T19:59:33.994330+0300 || DEBUG || ---LOGED---
2023-10-30T20:09:19.466192+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T20:09:19.467192+0300 || DEBUG || ---LOGED---
2023-10-30T20:09:32.515235+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x000001D25F7EB1F0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x000001D25FBD44A0> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:09:36.121119+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x000001D25F7EB1F0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x000001D25FBD42E0> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:10:29.743690+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T20:10:29.744690+0300 || DEBUG || ---LOGED---
2023-10-30T20:10:41.199005+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x00000158FC1CB1F0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x00000158FC5B44A0> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:12:46.204829+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T20:12:46.205829+0300 || DEBUG || ---LOGED---
2023-10-30T20:12:56.276422+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x0000022EBA5FA3E0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x0000022EBA9E4580> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:13:10.791371+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x0000022EBA5FA3E0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x0000022EBA9E43C0> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:14:09.581281+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T20:14:09.582281+0300 || DEBUG || ---LOGED---
2023-10-30T20:14:27.887895+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T20:14:27.888896+0300 || DEBUG || ---LOGED---
2023-10-30T20:14:34.805490+0300 || DEBUG || NEW_GUILD --|-- <coroutine object Client.fetch_guild at 0x0000028503F371F0> | 1164886134137045022 --|-- <coroutine object Client.fetch_user at 0x0000028504324580> | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:21:54.599383+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-30T20:21:54.599383+0300 || DEBUG || ---LOGED---
2023-10-30T20:22:09.950170+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:22:17.081564+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> FAIL (incorrect language)
2023-10-30T20:22:19.730162+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> FAIL (incorrect language)
2023-10-31T21:53:04.761706+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-31T21:53:04.762706+0300 || DEBUG || ---LOGED---
2023-10-31T21:53:16.069733+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> FAIL (incorrect language)
2023-10-31T21:55:08.181024+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-10-31T21:55:08.181024+0300 || DEBUG || ---LOGED---
2023-10-31T21:55:18.941639+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> FAIL (incorrect language)
2023-11-03T15:32:30.434167+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-03T15:32:30.436168+0300 || DEBUG || ---LOGED---
2023-11-03T15:33:05.393256+0300 || ERROR || An error has been caught in function 'on_guild_join', process 'MainProcess' (8924), thread 'MainThread' (5988):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 112, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x000001D3521F5300>
    └ <discord.client.Client object at 0x000001D350A91D10>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001D3522E4720>
    │       └ <function run at 0x000001D350AD7060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001D3522B9D50>
           │      └ <function Runner.run at 0x000001D350B20AE0>
           └ <asyncio.runners.Runner object at 0x000001D3522E2150>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001D350B1A5C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001D3522E2150>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001D35102A480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001D350B20360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001D350AD0400>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=2>,)
          └ <function on_guild_join at 0x000001D3522E4680>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 108, in on_guild_join
    new_guild(['NEW_GUILD', await client.fetch_guild(guild.id), guild.id])
    │                             │      │           │     │    │     └ <member 'id' of 'Guild' objects>
    │                             │      │           │     │    └ <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=2>
    │                             │      │           │     └ <member 'id' of 'Guild' objects>
    │                             │      │           └ <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=2>
    │                             │      └ <function Client.fetch_guild at 0x000001D3521FC860>
    │                             └ <discord.client.Client object at 0x000001D350A91D10>
    └ <function new_guild at 0x000001D3522D7D80>

TypeError: new_guild() missing 2 required positional arguments: 'emoji' and 'log'
2023-11-03T15:33:55.328667+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> FAIL (incorrect language)
2023-11-03T15:38:26.159914+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-03T15:38:26.159914+0300 || DEBUG || ---LOGED---
2023-11-03T15:38:39.283307+0300 || ERROR || An error has been caught in function 'on_guild_join', process 'MainProcess' (6960), thread 'MainThread' (15260):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 112, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x000001C366A35300>
    └ <discord.client.Client object at 0x000001C3652E1D10>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x000001C366B24720>
    │       └ <function run at 0x000001C365327060>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x000001C366AF9D50>
           │      └ <function Runner.run at 0x000001C365370AE0>
           └ <asyncio.runners.Runner object at 0x000001C366AC7BD0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001C36536A5C0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001C366AC7BD0>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001C36586A480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001C365370360>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001C365320400>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=2>,)
          └ <function on_guild_join at 0x000001C366B24680>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 108, in on_guild_join
    new_guild(['NEW_GUILD', await client.fetch_guild(guild.id), guild.id])
    │                             │      │           │     │    │     └ <member 'id' of 'Guild' objects>
    │                             │      │           │     │    └ <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=2>
    │                             │      │           │     └ <member 'id' of 'Guild' objects>
    │                             │      │           └ <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=2>
    │                             │      └ <function Client.fetch_guild at 0x000001C366A3C860>
    │                             └ <discord.client.Client object at 0x000001C3652E1D10>
    └ <function new_guild at 0x000001C366B17D80>

TypeError: new_guild() missing 2 required positional arguments: 'emoji' and 'log'
2023-11-03T15:38:41.913034+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-04T23:02:19.768166+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-04T23:02:19.769166+0300 || DEBUG || ---LOGED---
2023-11-04T23:03:55.662622+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-04T23:04:56.561798+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-04T23:04:56.562799+0300 || DEBUG || ---LOGED---
2023-11-04T23:05:04.133708+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-04T23:05:06.681071+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-04T23:05:11.215657+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-04T23:05:14.980736+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T18:31:15.570981+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T18:31:15.571981+0300 || DEBUG || ---LOGED---
2023-11-27T18:33:00.714622+0300 || CRITICAL || ERROR IN LANGUAGE_INITIALIZATION: 
2023-11-27T18:36:55.098099+0300 || CRITICAL || ERROR IN LANGUAGE_INITIALIZATION: 
2023-11-27T18:37:24.092299+0300 || CRITICAL || ERROR IN LANGUAGE_INITIALIZATION: 
2023-11-27T18:39:48.571141+0300 || CRITICAL || ERROR IN LANGUAGE_INITIALIZATION: [Errno 2] No such file or directory: 'localization/content.json'
2023-11-27T19:04:22.257699+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:04:22.258699+0300 || DEBUG || ---LOGED---
2023-11-27T19:04:48.746953+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:06:05.992717+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:06:05.993717+0300 || DEBUG || ---LOGED---
2023-11-27T19:06:18.921277+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:08:43.485783+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:08:43.486783+0300 || DEBUG || ---LOGED---
2023-11-27T19:08:52.030849+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:10:13.562758+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:10:13.563759+0300 || DEBUG || ---LOGED---
2023-11-27T19:10:22.848693+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:13:20.559634+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:13:20.560635+0300 || DEBUG || ---LOGED---
2023-11-27T19:13:36.776582+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:13:36.777582+0300 || DEBUG || ---LOGED---
2023-11-27T19:13:47.166042+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:13:51.715625+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T19:17:00.653524+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:17:00.654525+0300 || DEBUG || ---LOGED---
2023-11-27T19:17:13.173855+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:17:17.490044+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T19:18:52.166610+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:18:52.167611+0300 || DEBUG || ---LOGED---
2023-11-27T19:18:59.254589+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:19:12.793521+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T19:20:55.879566+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:20:55.879566+0300 || DEBUG || ---LOGED---
2023-11-27T19:21:03.471566+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:21:19.756717+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T19:25:28.298521+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:25:28.299522+0300 || DEBUG || ---LOGED---
2023-11-27T19:25:36.320319+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:25:41.666550+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T19:28:50.885871+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:28:50.886871+0300 || DEBUG || ---LOGED---
2023-11-27T19:28:58.326486+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:29:03.021336+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T19:38:05.218191+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T19:38:05.219191+0300 || DEBUG || ---LOGED---
2023-11-27T19:38:22.754736+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T19:38:26.752353+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T19:38:58.301890+0300 || DEBUG || elisey_iz_kkr | elisey_iz_kkr --> /admins (success)
2023-11-27T21:16:08.729660+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:16:08.729660+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:16:08.730682+0300 || DEBUG || ---LOGED---
2023-11-27T21:16:25.087683+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T21:16:26.916329+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T21:16:42.719497+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:18:42.475575+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:18:42.476576+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:18:42.476576+0300 || DEBUG || ---LOGED---
2023-11-27T21:18:59.210976+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T21:19:02.337613+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T21:19:09.062599+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:20:26.761538+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:20:26.762539+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:20:26.762539+0300 || DEBUG || ---LOGED---
2023-11-27T21:20:36.912642+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T21:20:38.542603+0300 || DEBUG || Start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T21:20:45.907470+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:55:36.018989+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:55:36.018989+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:55:36.019989+0300 || DEBUG || ---LOGED---
2023-11-27T21:55:47.661629+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T21:55:49.423697+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T21:55:53.623994+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:56:01.380916+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:56:05.109093+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:56:25.795303+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:56:37.043582+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:56:47.894744+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T21:57:24.765035+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:57:24.766036+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T21:57:24.766036+0300 || DEBUG || ---LOGED---
2023-11-27T21:57:44.139054+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T21:57:46.064956+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T21:57:54.328931+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T22:14:50.451590+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:14:50.452590+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:14:50.452590+0300 || DEBUG || ---LOGED---
2023-11-27T22:15:07.919183+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T22:15:09.170473+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-27T22:15:17.410516+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T22:15:17.412517+0300 || ERROR || ERROR IN admins: /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
can only join an iterable
2023-11-27T22:18:25.912695+0300 || DEBUG || /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T22:18:25.913730+0300 || ERROR || ERROR IN admins: /админы --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
can only join an iterable
2023-11-27T22:37:01.788794+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:37:01.788794+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:37:01.788794+0300 || DEBUG || ---LOGED---
2023-11-27T22:37:17.379359+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T22:37:18.610369+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T22:37:29.358553+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (8248), thread 'MainThread' (14596):
Traceback (most recent call last):

  File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 121, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x0000017A906193A0>
    └ <discord.client.Client object at 0x0000017A8CF6D950>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x0000017A906EF420>
    │       └ <function run at 0x0000017A8EEDAFC0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x0000017A906DA020>
           │      └ <function Runner.run at 0x0000017A8EF30A40>
           └ <asyncio.runners.Runner object at 0x0000017A90709490>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000017A8EF2A520>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000017A90709490>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000017A8F04A520>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000017A8EF302C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000017A8EED4360>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1178781664462254242 channel=<TextChannel id=1167491479745343528 name='kkr_loot' position=3 nsfw=False news=False...
          └ <function on_message at 0x0000017A906EEDE0>

> File "c:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 64, in on_message
    await send_Embed(SCRIPTS[command](  log, language, conditions, GUILDS[guild_id], client  ))
          │          │       │          │    │         │           │      │          └ <discord.client.Client object at 0x0000017A8CF6D950>
          │          │       │          │    │         │           │      └ 1164886134137045022
          │          │       │          │    │         │           └ {1164886134137045022: <guilds.Guilds object at 0x0000017A8FB6BD10>}
          │          │       │          │    │         └ []
          │          │       │          │    └ 'eng'
          │          │       │          └ ('/admins', <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=None>, 1164886134137045022, 'elis...
          │          │       └ 'admins'
          │          └ {'admins': <function admins at 0x0000017A906EE2A0>}
          └ <function on_message.<locals>.send_Embed at 0x0000017A90A8A020>

TypeError: admins() takes 4 positional arguments but 5 were given
2023-11-27T22:41:49.667446+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:41:49.668446+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:41:49.668446+0300 || DEBUG || ---LOGED---
2023-11-27T22:42:03.140439+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T22:42:04.097208+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T22:42:08.422516+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-27T22:42:08.423516+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
'NoneType' object has no attribute 'admins'
2023-11-27T22:45:55.331258+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:45:55.332257+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:45:55.332257+0300 || DEBUG || ---LOGED---
2023-11-27T22:46:11.915309+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T22:46:12.657289+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T22:46:16.200260+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
'coroutine' object has no attribute 'admins'
2023-11-27T22:48:55.725705+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:48:55.726705+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-27T22:48:55.726705+0300 || DEBUG || ---LOGED---
2023-11-27T22:49:04.411829+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-27T22:49:06.229302+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-27T22:49:14.604320+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
'coroutine' object has no attribute 'admins'
2023-11-28T23:50:26.415643+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-28T23:50:26.418643+0300 || DEBUG || ---LOGED---
2023-11-28T23:51:28.854477+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-28T23:51:44.564398+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (eng)
2023-11-28T23:54:55.936431+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-28T23:54:55.937431+0300 || DEBUG || ---LOGED---
2023-11-28T23:55:18.291008+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-28T23:55:21.254181+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-28T23:57:26.618174+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-28T23:57:26.620174+0300 || DEBUG || ---LOGED---
2023-11-28T23:58:08.461429+0300 || DEBUG || NEW_GUILD --|-- Тест | 1164886134137045022 --> SUCCESS
2023-11-28T23:58:09.500666+0300 || DEBUG || start_select_language --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS (ru)
2023-11-29T00:04:30.838978+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:04:30.839979+0300 || DEBUG || ---LOGED---
2023-11-29T00:05:21.041100+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:05:21.043100+0300 || DEBUG || ---LOGED---
2023-11-29T00:07:26.460456+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:07:26.461456+0300 || DEBUG || ---LOGED---
2023-11-29T00:07:29.888228+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
sequence item 0: expected str instance, coroutine found
2023-11-29T00:31:40.525096+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:31:40.527096+0300 || DEBUG || ---LOGED---
2023-11-29T00:31:42.698585+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
sequence item 0: expected str instance, coroutine found
2023-11-29T00:38:13.667082+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:38:13.668081+0300 || DEBUG || ---LOGED---
2023-11-29T00:38:19.080787+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
sequence item 0: expected str instance, coroutine found
2023-11-29T00:40:56.177212+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
sequence item 0: expected str instance, coroutine found
2023-11-29T00:41:46.084261+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:41:46.086262+0300 || DEBUG || ---LOGED---
2023-11-29T00:41:51.637512+0300 || ERROR || ERROR IN admins: /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892
sequence item 0: expected str instance, coroutine found
2023-11-29T00:43:09.011873+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:43:09.013874+0300 || DEBUG || ---LOGED---
2023-11-29T00:43:11.626462+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (5992), thread 'MainThread' (17816):
Traceback (most recent call last):

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │         └ <code object <module> at 0x0000020565DF2EF0, file "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\l...
           └ <function _run_code at 0x0000020565FCA020>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x0000020565DF2EF0, file "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\l...

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
    │   └ <function main at 0x0000020568ABCFE0>
    └ <module 'debugpy.server.cli' from 'c:\\Users\\kroto\\.vscode\\extensions\\ms-python.python-2023.20.0\\pythonFiles\\lib\\pytho...

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
    └ <function run_file at 0x0000020568ABCD60>

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
    │     │        └ 'C:\\Users\\kroto\\OneDrive\\Документы\\Python\\KKR_loot\\main.py'
    │     └ <function run_path at 0x00000205686E2A20>
    └ <module '_pydevd_bundle.pydevd_runpy' from 'c:\\Users\\kroto\\.vscode\\extensions\\ms-python.python-2023.20.0\\pythonFiles\\l...

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           │                │     │             └ '__main__'
           │                │     └ None
           │                └ <code object <module> at 0x00000205683CA2C0, file "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 1>
           └ <function _run_module_code at 0x00000205686E2660>

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    │         │     │            └ None
    │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'C:\\Users\\kr...
    │         └ <code object <module> at 0x00000205683CA2C0, file "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 1>
    └ <function _run_code at 0x00000205686E2200>

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'C:\\Users\\kr...
         └ <code object <module> at 0x00000205683CA2C0, file "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 1>

  File "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 124, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x0000020569EDA200>
    └ <discord.client.Client object at 0x0000020568BA88D0>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x0000020569FB80E0>
    │       └ <function run at 0x00000205695193A0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x0000020569F4B2E0>
           │      └ <function Runner.run at 0x0000020569519760>
           └ <asyncio.runners.Runner object at 0x000002056992B490>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000002056950F060>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002056992B490>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002056959D6C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000020569518E00>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002056949C360>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1179175687668629646 channel=<TextChannel id=1167491479745343528 name='kkr_loot' position=3 nsfw=False news=False...
          └ <function on_message at 0x0000020569F87B00>

> File "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 73, in on_message
    admins(log, language,
    │      │    └ 'eng'
    │      └ ('/admins', <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=None>, 1164886134137045022, 'elis...
    └ <function admins at 0x0000020569F86D40>

  File "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\scripts.py", line 85, in admins
    content = LANGUAGE[language]['admins_content'] + '\n'.join(admins)
              │        │                                       └ [<coroutine object Client.fetch_user at 0x0000020569FC5460>]
              │        └ 'eng'
              └ {'eng': {'error_title': 'ERROR!', 'error_content': 'Unexpected error. The developer has already received a report about your ...

TypeError: sequence item 0: expected str instance, coroutine found
2023-11-29T00:53:00.891745+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:53:00.893744+0300 || DEBUG || ---LOGED---
2023-11-29T00:55:25.960283+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:55:25.961283+0300 || DEBUG || ---LOGED---
2023-11-29T00:55:30.299227+0300 || ERROR || An error has been caught in function 'on_message', process 'MainProcess' (2156), thread 'MainThread' (7544):
Traceback (most recent call last):

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │         └ <code object <module> at 0x0000020802752EF0, file "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\l...
           └ <function _run_code at 0x000002080292A020>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x0000020802752EF0, file "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\l...

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
    │   └ <function main at 0x000002080543CFE0>
    └ <module 'debugpy.server.cli' from 'c:\\Users\\kroto\\.vscode\\extensions\\ms-python.python-2023.20.0\\pythonFiles\\lib\\pytho...

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
    └ <function run_file at 0x000002080543CD60>

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
    │     │        └ 'C:\\Users\\kroto\\OneDrive\\Документы\\Python\\KKR_loot\\main.py'
    │     └ <function run_path at 0x0000020805062A20>
    └ <module '_pydevd_bundle.pydevd_runpy' from 'c:\\Users\\kroto\\.vscode\\extensions\\ms-python.python-2023.20.0\\pythonFiles\\l...

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           │                │     │             └ '__main__'
           │                │     └ None
           │                └ <code object <module> at 0x0000020804D54600, file "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 1>
           └ <function _run_module_code at 0x0000020805062660>

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    │         │     │            └ None
    │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'C:\\Users\\kr...
    │         └ <code object <module> at 0x0000020804D54600, file "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 1>
    └ <function _run_code at 0x0000020805062200>

  File "c:\Users\kroto\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'C:\\Users\\kr...
         └ <code object <module> at 0x0000020804D54600, file "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 1>

  File "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 124, in <module>
    client.run(input('token: '))
    │      └ <function Client.run at 0x0000020806856200>
    └ <discord.client.Client object at 0x000002080552CB50>

  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
    │       │   └ <function Client.run.<locals>.runner at 0x00000208069340E0>
    │       └ <function run at 0x0000020805E993A0>
    └ <module 'asyncio' from 'C:\\Users\\kroto\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Client.run.<locals>.runner at 0x00000208068CB2E0>
           │      └ <function Runner.run at 0x0000020805E99760>
           └ <asyncio.runners.Runner object at 0x0000020806933F50>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Client.run.<locals>.runner() running at C:\Users\kroto\AppData\Local\Programs\Python\Python...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000020805E93060>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000020806933F50>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000020805F1D6C0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000020805E98E00>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000020805E20360>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\kroto\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
          │     │       └ {}
          │     └ (<Message id=1179178785346682933 channel=<TextChannel id=1167491479745343528 name='kkr_loot' position=3 nsfw=False news=False...
          └ <function on_message at 0x0000020806907B00>

> File "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\main.py", line 73, in on_message
    admins(log, language,
    │      │    └ 'eng'
    │      └ ('/admins', <Guild id=1164886134137045022 name='Тест' shard_id=0 chunked=False member_count=None>, 1164886134137045022, 'elis...
    └ <function admins at 0x0000020806906D40>

  File "C:\Users\kroto\OneDrive\Документы\Python\KKR_loot\scripts.py", line 85, in admins
    content = LANGUAGE[language]['admins_content'] + '\n'.join(admins)
              │        │                                       └ [<User id=710395621688737892 name='elisey_iz_kkr' global_name='Elisey' bot=False>]
              │        └ 'eng'
              └ {'eng': {'error_title': 'ERROR!', 'error_content': 'Unexpected error. The developer has already received a report about your ...

TypeError: sequence item 0: expected str instance, User found
2023-11-29T00:56:44.379368+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:56:44.381369+0300 || DEBUG || ---LOGED---
2023-11-29T00:58:39.440100+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T00:58:39.441100+0300 || DEBUG || ---LOGED---
2023-11-29T18:48:10.159282+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T18:48:10.163283+0300 || DEBUG || ---LOGED---
2023-11-29T18:48:28.854914+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-29T18:49:45.026043+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T18:49:45.028044+0300 || DEBUG || ---LOGED---
2023-11-29T18:49:53.325315+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
2023-11-29T18:51:22.383061+0300 || DEBUG || ---LANGUAGE_INITIALIZATION---
2023-11-29T18:51:22.385062+0300 || DEBUG || ---LOGED---
2023-11-29T18:51:26.285226+0300 || DEBUG || /admins --|-- Тест | 1164886134137045022 --|-- elisey_iz_kkr | 710395621688737892 --> SUCCESS
